# -*- coding: utf-8 -*-
"""basic RNN and LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLWnkbklWg9LAGK3cubVwfWNYlBimdJn
"""

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def create_dataset(seq_length=5, total_samples=1000):
    X = []
    y = []
    for _ in range(total_samples):
        start = np.random.rand()
        seq = np.array([start + i*0.1 for i in range(seq_length+1)])
        X.append(seq[:-1])
        y.append(seq[-1])
    return np.array(X), np.array(y)

seq_length = 5
X, y = create_dataset(seq_length)

# reshape for RNN input: (samples, timesteps, features)
X = X.reshape((X.shape[0], X.shape[1], 1))
y = y.reshape((-1, 1))

print("X shape:", X.shape)
print("y shape:", y.shape)

df = pd.DataFrame(X.reshape(-1, seq_length),
                  columns=[f"x_{i}" for i in range(seq_length)])
df["y"] = y
df.head()

def build_rnn_model():
  model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=15,
                             activation='tanh',
                             input_shape=(seq_length, 1)
                             ),
    tf.keras.layers.Dense(units=1)
  ])
  model.compile(optimizer='adam', loss='mse', metrics=['mse'])
  return model

model = build_rnn_model()
model.summary()

history_rnn = model.fit(
    X, y,
    epochs=5,
    batch_size=32,
    verbose=1,
    validation_split=0.2
)

pred_rnn= model.predict(X[:10])
# print("predictions:",pred_rnn)
# print("actual:", y[:10])

#convert this to dataframe
df_pred = pd.DataFrame(pred_rnn, columns=["prediction"])
df_pred["actual"] = y[:10]
df_pred

255*4

def build_lstm_model():
  model_lstm = tf.keras.Sequential([
    tf.keras.layers.LSTM(units=15,
                             input_shape=(seq_length, 1)
                             ),
    tf.keras.layers.Dense(units=1)
  ])
  model_lstm.compile(optimizer='adam', loss='mse', metrics=['mse'])
  return model_lstm

model_lstm = build_lstm_model()
model_lstm.summary()

history_lstm = model_lstm.fit(
    X, y,
    epochs=5,
    batch_size=32,
    verbose=1,
    validation_split=0.2
)

pred_lstm= model_lstm.predict(X[:10])
# print("predictions:",pred_lstm)
# print("actual:", y[:10])
#convert this to dataframe
df_pred = pd.DataFrame(pred_lstm, columns=["prediction"])
df_pred["actual"] = y[:10]
df_pred

plt.plot(history_rnn.history['val_loss'], label='rnn')
plt.plot(history_lstm.history['val_loss'], label='lstm')
plt.legend()
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.show()

