# -*- coding: utf-8 -*-
"""MNIST Neural Network Predictin with Tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UK047I5-76f_8lZBU-f066qbccoi9VmL

# MNIST Neural Network Predictin with Tensorflow
Create a predictive model using a sequential neural network with appropriate weights for the MNIST dataset.

## Importing Libraries
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.models import Sequential
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense, Flatten

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

"""## Load and normalize data

Load the MNIST dataset and normalize the pixel values.

"""

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train / 255.0
x_test = x_test / 255.0

print("MNIST dataset loaded and normalized.")
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

plt.figure(figsize=(6, 3)) # Create a new figure with a specified size

# this is how we are printing example images from our dataset
for i in range(10): # Loop through each digit from 0 to 9
    # Find the index of the first occurrence of the current digit in the training labels
    digit_index = np.where(y_train == i)[0][0]
    plt.subplot(2, 5, i + 1) # Create a subplot for each digit (2 rows, 5 columns)
    plt.imshow(x_train[digit_index], cmap='gray') # Display the image of the digit
    # Set the title of the subplot to the digit number and image shape
    plt.title(f"No. {i} {x_train[digit_index].shape}")
    plt.axis('off') # Turn off the axis for the subplot
plt.tight_layout() # Adjust the layout to prevent titles/labels from overlapping
plt.show() # Display the plot

"""## Define model

Define a sequential neural network model.

"""

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.summary()

128*(784+1)

10*(128+1)

"""Define a Functioal API neural network model."""

# Define input
inputs = Input(shape=(28, 28))

# Connect layers manually
x = Flatten()(inputs)
x = Dense(128, activation='relu')(x)
outputs = Dense(10, activation='softmax')(x)

# Define the model
model = Model(inputs=inputs, outputs=outputs)

model.summary()

"""## Compile model

Compile the model with an appropriate optimizer, loss function, and metrics.

"""

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

"""## Train model

Train the model on the training data.

"""

history = model.fit(x_train, y_train, epochs=10, validation_split=0.2)

plt.figure(figsize=(6, 3))

# Plot accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""## Evaluate model

Evaluate the model on the test data.
"""

loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test loss: {loss}")
print(f"Test accuracy: {accuracy}")

"""## Classification Metrics

Compute classification metrics for the model.
"""

# Get predictions
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

# Compute classification report
print("Classification Report:")
print(classification_report(y_test, y_pred_classes))

"""## Visualize Confusion Matrix

Visualize the confusion matrix.
"""

cm = confusion_matrix(y_test, y_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()



model2 = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(254, activation='relu'),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model2.summary()
model2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
history2 = model2.fit(x_train, y_train, epochs=10, validation_split=0.15)
loss, accuracy = model2.evaluate(x_test, y_test)
print(f"Test loss: {loss}")
print(f"Test accuracy: {accuracy}")
# Get predictions
y_pred = model.predict(x_test)
y_pred_classes = np.argmax(y_pred, axis=1)

print("Classification Report:")
print(classification_report(y_test, y_pred_classes))
print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

(60000,28,28)
(60000,28*28)

# applying logistic regression on MNIST data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(x_train.reshape(-1, 28*28), y_train)
y_pred = lr.predict(x_test.reshape(-1, 28*28))
accuracy_score(y_test, y_pred)

784 -> 100

60000,784
60000,100

# first apply pca getting 100 features then applying logistic regression on MNIST data
from sklearn.decomposition import PCA
pca = PCA(n_components=100)
pca.fit(x_train.reshape(-1, 28*28))

x_train_pca = pca.transform(x_train.reshape(-1, 28*28))
x_test_pca = pca.transform(x_test.reshape(-1, 28*28))

lr = LogisticRegression()
lr.fit(x_train_pca, y_train)
y_pred = lr.predict(x_test_pca)
accuracy_score(y_test, y_pred)

# first apply pca getting 100 features then applying support vector classifier on MNIST data
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

pca = PCA(n_components=100)
pca.fit(x_train.reshape(-1, 28*28))
x_train_pca = pca.transform(x_train.reshape(-1, 28*28))
x_test_pca = pca.transform(x_test.reshape(-1, 28*28))

lr = SVC()
lr.fit(x_train_pca, y_train)
y_pred = lr.predict(x_test_pca)
accuracy_score(y_test, y_pred)

"""1. Apply the feed forward neural network on mnist dataset with 4 layers and compare it with pca + randomforestclassifier"""

