# -*- coding: utf-8 -*-
"""Day5- PBEL3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8t5peJPWGENPGUYDOFp9eL-es4wEVHY

## Ollama install
Installs ollama and run it as a subprocess
"""

!sudo apt update
!sudo apt-get install zstd
!sudo apt install -y pciutils
!curl -fsSL https://ollama.com/install.sh | sh

import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

"""## Pulling Models"""

!ollama pull granite4.1:3b
# !ollama pull llama3.2
# !ollama pull gemma4:e2b

!ollama list

!pip install langchain-ollama

"""## Using Langchain and ollama"""

from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama.llms import OllamaLLM
from IPython.display import Markdown

template = """Question: {question}

Answer: Let's think step by step."""

prompt = ChatPromptTemplate.from_template(template)

model = OllamaLLM(model="llama3.2")

chain = prompt | model

display(Markdown(chain.invoke({"question": "What's the length of hypotenuse in a right angled triangle"})))

!ollama run llama3.2

