# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIe6XBxszzNHxDAoSGiQyGn_0Q7I27sr

1. **Make a function to print a hollow square pattern.**

   * Take the side length as an argument.
   * Example for length = 5:

   ```
   *****
   *   *
   *   *
   *   *
   *****
   ```
"""

def pattern(length):
  for i in range(length):
    for j in range(length):
      if(i==0 or i==length-1 or j==0 or j==length-1):
        print("*",end="")
      else:
        print(" ",end="")
    print()
pattern(5)

"""2. **Create 4 variables and apply all assignment operators.**

   * Use operators like `=`, `+=`, `-=`, `*=`, `/=`, `//=`, `%=`, and `**=`.
   * Print the result after each operation.
"""

def operations(a,b,c,d):
  a=10
  print("the value of a=",a)
  b+=a
  print("the value of b+=",b)
  c-=a
  print("the value of c-=",c)
  d*=a
  print("the value of d*=",d)
  d/=a
  print("the value of d/=",d)
  d//=a
  print("the value of d//=",d)
  d%=a
  print("the value of d%=",d)
  d**=2
  print("the value of d**=",d)
operations(10,20,30,40)

"""3. **Make a function to count vowels in a string.**

   * Take a string as an argument.
   * Return the total number of vowels.
"""

def vowels(word):
  c=0
  for i in word:
    if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
      c+=1
  return c
print(vowels("hello divankar"))

"""4. **Make a class called `Calculator` and add 3 functions:**

   * Addition
   * Subtraction
   * Multiplication
   * Take numbers as arguments.
"""

class calculator:
  def add(self,a,b):
    return a+b
  def sub(self,a,b):
    return a-b
  def mul(self,a,b):
    return a*b
obj=calculator()
print(obj.add(10,20))
print(obj.sub(190,20))
print(obj.mul(10,20))

type(calculator)

"""5. **Make a function to find the largest number in a list without using `max()`.**

   * Take a list as an argument.
   * Return the largest value.
"""

def maxnum(list):
  max=list[0]
  for i in list:
    if(i>max):
      max=i
  return max
print(maxnum([1,2,30,4,5,6,7,80,9,10]))

"""6. **Create a class called `StringTools` and add 2 functions:**

   * Convert a string to uppercase without using `upper()`.
   * Count the number of words in a string.
"""

class StringTools:
  def upper(self,word):
    for i in word:
      if(ord(i)>=97 and ord(i)<=122):
        print(chr(ord(i)-32),end="")
      else:
        print(i,end="")
  def countword(self,sentence):
    print(len(sentence.split()))
w=StringTools()
w.upper("hello World")
print()
w.countword("hello World ")

"""7. **Make a function to check whether a number is prime.**

   * Take a number as an argument.
   * Return `True` or `False`.
"""

def isprime(num):
  for i in range(2,num):
    if(num%i==0):
      return False
  return True
print(isprime(10))

"""8. **Create 2 lists and perform the following operations:**

   * Concatenate both lists.
   * Find common elements using loops.
   * Find unique elements from both lists.
"""

def myfun(list1 ,list2):
  list3=list1+list2
  print(list3)
  common=[]
  unique=[]
  for i in list1:
    for j in list2:
      if(i==j):
        common.append(i)
  print(common)
myfun([1,2,3,4],[3,4,5,6])

"""9. **Make a function to calculate the factorial of a number using a loop.**

   * Take a number as an argument.
   * Do not use recursion or built-in libraries.
"""

def factorial(n):
    result = 1

    for i in range(1, n + 1):
        result *= i

    return result

num = int(input("Enter a number: "))
print("Factorial =", factorial(num))

"""10. **Make a class called `Student` with the following functions:**

    * Add student name and marks.
    * Display student details.
    * Check whether the student passed (marks ≥ 40).
"""

class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def display_details(self):
        print("Student Name:", self.name)
        print("Marks:", self.marks)

    def check_pass(self):
        if self.marks >= 40:
            print("Result: Pass")
        else:
            print("Result: Fail")


# Input
name = input("Enter student name: ")
marks = int(input("Enter marks: "))

# Create object
student = Student(name, marks)

# Display details
student.display_details()

# Check pass/fail
student.check_pass()