# -*- coding: utf-8 -*-
"""Generative AI tools, services and Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsP2o8W1P2Njz0rA8yHP1qU-9YtKGpq1
"""

# Overview of GenAI platforms
# What is a generative AI platform.?
# These are the platforms that provide pre-trained AI models via APIs so developers dont train model from scratch

# Major platforms
# Some of the most widely used platforms are:

# 1. OpenAI
# - Models: GPT(text),DALL.E(image),Whisper(speech)
# - Used for: Chatbots, content generation

# 2. Hugging Face
# - Provides open-source models (BERT, LLaMA etc)
# - Easy deployment via Spaces

# 3. IBM watson
# - Enterprise AI tools
# - NLP, chatbots, analytics

# 4. Google Cloud AI
# - Vertex AI, PaLM models
# - Strong in scalability

# Generative AI platforms provide ready to use models
# Reduce cost, time and complexity
# Access via APIs

# Using APIs for text, image,and speech
# APIs: Application programming interface -> Allows your app to talk to AI models

# Example: Text generation using OpenAI

from openai import OpenAI
# importing the openAI class from openAI library
# This library allows python to communicate with AI models


client = OpenAI(api_key = 'your_api_key')
# Creating a 'client' object
# Client is sending requests to OpenAI servers

response = client.chat.completions.create(
# We are calling the chat API
# .create() -> Generate a response

    model = 'gpt-4o-mini',
    # Choosing which AI model to use
    # "gpt-4o-mini": fast + cheaper version of GPT

    messages = [{"role":"user","content":"what is tsunami"}]
    # This is the input we sent to AI
    # role: user -> who is speaking (you)
    # "content" -> what are you asking
)

print(response.choices[0].message.content)
# This line prints the AI reply or the output of the model
# response -> full o/p from AI
# .choices -> list of possible answers
# [0] -> takes the first answer
# .message -> message object
# .content -> actual text

# Image generation (DALL.E)
import base64

response = client.images.generate(
    model = 'gpt-image-1',
    prompt = 'garp one piece'
)
image_base64 = response.data[0].b64_json
with open("image.png","wb") as f:
  f.write(base64.b64decode(image_base64))
print("Image saved successfully")

from PIL import Image

img = Image.open("image.png")
img.show()

from google.colab import files

files.download("image.png")

# Speech to text(whisper)
audio_file = open("speech.mp3",'rb')

transcript = client.audio.transcriptions.create(
    model = 'whisper-1',
    file = audio_file
)

print(transcript.text)

# APIs connect frontend -> AI model
# Types: Text API, Image API, Speech API

# Applications with CHATGPT, DALL.E, TTS/STT
# Chatgpt: Chatbots, coding help, image generate, content creation
# DALL.E : Image generation
# TTS: Voice Assistant
# STT: Voice input systems

# Example: Chatbot Logic

user_input = input("Whats on your mind.?: ")

response = client.chat.completions.create(
    model = 'gpt-4o-mini',
    messages = [{'role':"user","content":user_input}]
)

print("Bot:",response.choices[0].message.content)

# Applications
# 1. Customer support bots
# 2. AI tutors
# 3. Resume generator
# 4. Voice assistant

