# -*- coding: utf-8 -*-
"""Revision_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzfEKZU0BDpb5vQhdS2w8Ej1TP6EYdnF
"""

# Q1: Tokenization
# WAP to tokenize a sentence. sentence = 'Natural language processing is amazing'
sentence = 'Natural language processing is amazing'
tokens = sentence.split()
print("Tokens:",tokens)

# Q2: Stemming
# Apply stemming using NLTK
# ['running','jumps','easily','flying']
words = ['running','jumps','easily','flying']
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stemmed = [ps.stem(word) for word in words]
print("Stemmed words:",stemmed)

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
# Q3: Lemmatization
# Perform lemmatization using NLTK
# ['running','better','cars']
words = ['running','better','cars']
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(word,pos='v') for word in words]
print('Lemmatized words: ', lemmatized)

# Q4: TF-IDF Representation
# Convert text into TF-IDF features
# ["I love machine learning",
#  "Machine learning is fun",
#  "I am a coder"]
corpus = ["I love machine learning",
"Machine learning is fun",
"I am a coder"]

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print('Feature Names:',vectorizer.get_feature_names_out())
print('Matrix:\n',X.toarray())

!pip install gensim
# Q5: Word2Vec Embeddings
# Train a simple Word2Vec model
# sentences = [["i",'love','nlp'],['nlp','is','fun'],['i','enjoy','learning']]
sentences = [["i",'love','nlp'],
             ['nlp','is','fun'],
             ['i','enjoy','learning']]
# We are importing Word2Vec model from gensim library
from gensim.models import Word2Vec

model = Word2Vec(sentences,vector_size=50,window=2,min_count=1)
# sentences: i/p data, vector_size = each word has been converted into 50 dimensional vectors, window: context window, min_count=1 means includes all words

print("Vectors for nlp:",model.wv['nlp'])

# Q.6 Simple RNN model (Keras)
# Build a simple RNN for sequence data

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,Dense

model = Sequential([
    SimpleRNN(32,input_shape=(10,1)),
    Dense(1,activation='sigmoid')
])

model.compile(optimizer='adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.summary()

# Q.7 Bag of Words
# Create a bag of words representation using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Sample sentences
documents = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love Python"
]

# Create CountVectorizer object
cv = CountVectorizer()

# Fit and Transform the documents
X = cv.fit_transform(documents)

# Print Vocabulary
print("Vocabulary:")
print(cv.vocabulary_)

# Print Feature Names
print("\nFeature Names:")
print(cv.get_feature_names_out())

# Print Bag of Words Matrix
print("\nBag of Words Matrix:")
print(X.toarray())

# Q.8 POS tagging
# Perform Part of Speech tagging using NLTK
# Import NLTK
import nltk

# Download required resources (run only once)
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

# Sample sentence
sentence = "The quick brown fox jumps over the lazy dog."

# Tokenize the sentence into words
words = nltk.word_tokenize(sentence)

# Perform POS Tagging
pos_tags = nltk.pos_tag(words)

# Display the result
print("Words:")
print(words)

print("\nPart of Speech Tags:")
print(pos_tags)

# Q.9 Padding in sequence
# Apply padding to sequence using keras

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample sentences
sentences = [
    "I love machine learning",
    "Deep learning is amazing",
    "Python is easy"
]

# Create Tokenizer
tokenizer = Tokenizer()

# Fit the tokenizer on the text
tokenizer.fit_on_texts(sentences)

# Convert text into sequences
sequences = tokenizer.texts_to_sequences(sentences)

print("Word Index:")
print(tokenizer.word_index)

print("\nSequences:")
print(sequences)

# Apply Padding
padded_sequences = pad_sequences(sequences, padding='post')

print("\nPadded Sequences:")
print(padded_sequences)