# -*- coding: utf-8 -*-
"""Day1-PBEL3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlm-WRs6BBkmrm_R9heqOmzO7BrcsCtj
"""

print("hello")

pi= 3.14

print(pi)

"""1. Make a Function for creating a diamond get edge length as an argument.

2. Make 3 variables and apply all arithmatic operations and comparision operations.

3. Make a function to reverse a string without slicing using for loop take string as an argument.

4. Make a class and add 2 functions in that class:
  - to check a palindrome
  - to check string length
"""

def create_diamond(edge_length):
    if edge_length <= 0:
        print("Edge length must be a positive integer.")
        return
    # Upper part of the diamond
    for i in range(1, edge_length + 1):
        print(" " * (edge_length - i) + "* " * i)
    # Lower part of the diamond
    for i in range(edge_length - 1, 0, -1):
        print(" " * (edge_length - i) + "* " * i)

create_diamond(5)

create_diamond(0)
create_diamond(-1)
create_diamond(8)
create_diamond(12)

a = 20
b = 10
c = 5

# Arithmetic Operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * c)
print("Division:", a / b) # float division
print("Floor Division:", a // c) # integer division
# floor value of i.e 4.4 is 4
# ceil value of i.e 4.4 is 5
print("Modulus:", a % c)
print("Power:", b ** 2)

# Comparison Operations
print("a == b :", a == b)
print("a != b :", a != b)
print("a > b :", a > b)
print("a < b :", a < b)
print("a >= c :", a >= c)
print("b <= c :", b <= c)

def reverse_string(str1):
  rev = ""
  for ch in str1:
    rev = ch + rev
  return rev

reverse_string("ehuwkc")

"""Make a class and add 2 functions in that class:

to check a palindrome

to check string length
"""

class stringutils:
  def __init__(self,string):
    self.string = string
  def palindrom(self):
    return self.string == self.string[::-1]
  def srtlength(self):
    return len(self.string)

obj = stringutils("HappyppaH")
print(obj.palindrom())
print(obj.srtlength())
obj.string

class stringutils:
  def __init__(self,string):
    self.string = string
  def palindrom(self):
    return self.string == self.string[::-1]
  def srtlength(self):
    return len(self.string)

obj = stringutils("Happy")
pla= obj.palindrom()
leng = obj.srtlength()
obj.string