# -*- coding: utf-8 -*-
"""NLP_Notebook_Classic_Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GxXre3LY7M4Y5v00Q4eiaShoqhN2RZD

# 📘 NLP Notebook
### With Definitions, Differences & Examples

## ✂️ Sentence vs Word Tokenization

### 📌 Sentence Tokenization
Breaking text into sentences.

**Example:**
"AI is powerful. It is everywhere."

→ ["AI is powerful.", "It is everywhere."]

### 📌 Word Tokenization
Breaking sentence into words.

→ ["AI", "is", "powerful"]

### 🔥 Difference
| Sentence Tokenization | Word Tokenization |
|----------------------|------------------|
| Splits into sentences | Splits into words |
| Higher level         | Lower level      |
"""

text = """
The war in Afghanistan was a prolonged armed conflict lasting from 2001 to 2021. It began with an invasion by a United States–led coalition under the name Operation Enduring Freedom in response to the September 11 attacks (9/11) carried out by the Taliban-allied and Afghanistan-based al-Qaeda. The Taliban were expelled from major population centers by American-led forces supporting the anti-Taliban Northern Alliance, thus toppling the Taliban-ruled Islamic Emirate. In 2004, the U.S.-backed Islamic Republic was established, but by then, the Taliban, led by founder Mullah Omar, had reorganized and begun an insurgency against the Afghan government and coalition forces. The conflict ended as the 2021 Taliban offensive reestablished the Islamic Emirate. It was the longest war in United States military history, surpassing the Vietnam War by six months.
Following 9/11, masterminded by al-Qaeda leader Osama bin Laden, American president George W. Bush demanded that the Taliban immediately extradite him to the United States and close down al-Qaeda's camps in Afghanistan; the Taliban refused and demanded evidence of bin Laden's guilt before offering to hand him over to a neutral country. The US dismissed these offers and proceeded with the invasion. After expelling the Taliban and their allies, the American-led coalition remained in Afghanistan, forming the International Security Assistance Force (ISAF)—sanctioned by the United Nations—with the goal of creating a new democratic authority in the country that would prevent the Taliban from returning to power.[68][failed verification] A new Afghan Interim Administration was established, and international rebuilding efforts were launched.[69] By 2003, the Taliban had reorganized and launched a widespread insurgency against the new Afghan government and coalition forces. Insurgents from the Taliban and other Islamist groups waged asymmetric warfare, fighting with guerrilla warfare in the countryside, suicide attacks against urban targets, and reprisals against perceived Afghan collaborators. By 2007, large parts of Afghanistan had been retaken by the Taliban.[70][71] In response, the coalition sent a major influx of troops for counter-insurgency operations, with a "clear and hold" strategy for villages and towns; this influx peaked in 2011, when roughly 140,000 foreign troops were operating under ISAF command across Afghanistan.[72]
"""
print(text)

import nltk
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger_eng')

from nltk.tokenize import sent_tokenize, word_tokenize
# text = "AI is powerful. It is everywhere."

print(sent_tokenize(text))
print(word_tokenize(text))
words = word_tokenize(text)
sent = sent_tokenize(text)

"""Intelligen intelligen
    34         34

stud stud stud
23    23   23

## 🌱 Stemming vs Lemmatization

### 📌 Stemming
Cuts words to root form (may be incorrect)

running → run  
studies → studi ❌

### 📌 Lemmatization
Returns meaningful root word

running → run  
studies → study ✅

### 🔥 Difference
| Stemming | Lemmatization |
|----------|--------------|
| Fast     | Slower       |
| Less accurate | More accurate |
| No context | Uses context |
"""

from nltk.stem import PorterStemmer, WordNetLemmatizer

# words = ["running", "studies", "Intelligence", "porter", "Finder", "keeper"]

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

for w in words:
    print("Stem:", stemmer.stem(w), "| Lemma:", lemmatizer.lemmatize(w))

"""
## 🚫 Stopwords

### 📌 Definition
Common words that don’t add much meaning.

Examples:
- is, the, and, in

### Why remove?
- Reduce noise
- Improve model performance
"""

from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize

# text = "This is a simple NLP example"
# words = word_tokenize(text)

filtered = [w for w in words if w.lower() not in stopwords.words('english')]
print(filtered)

filtered = [w for w in filtered if w.lower() not in [',','.','?','!']]
print(filtered)

filtered[3]

"AI is the power"
 1  2   3    4

4231

"""
## 📊 Count Vectorizer vs TF-IDF

### 📌 Count Vectorizer
Counts word frequency

"NLP is powerful powerful"
→ powerful = 2

### 📌 TF-IDF (Term Frequency-Inverse Document Frequency)

Components of TF-IDF:

1. Term Frequency (TF): Measures how frequently a word appears in a specific document.

2. Inverse Document Frequency (IDF): Measures how important a word is across all documents in the corpus. It reduces the weight of common words (e.g., "the", "a") and increases the weight of rare words.

Means:

- Weights important words higher

- Rare words → higher importance

### 🔥 Difference
| Count Vectorizer | TF-IDF |
|----------------|--------|
| Raw frequency  | Weighted importance |
| Simple         | More informative |
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
corpus = sent
corpus = ["NLP is powerful", "NLP is easy"]

cv = CountVectorizer()
tfidf = TfidfVectorizer()
print("Count:", cv.fit_transform(corpus).toarray())
print("TF-IDF:", tfidf.fit_transform(corpus).toarray())
print(cv.get_feature_names_out())
print(tfidf.get_feature_names_out())

# easy = 0
# is = 1
# NLP = 2
# powerful = 3

"""
## 🔗 N-grams

### 📌 Definition
Combination of N words together

Unigram → "AI"  
Bigram → "AI is"  
Trigram → "AI is powerful"

### Why important?
Context understanding

"not good" ≠ "good"
"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(1,3))
X = vectorizer.fit_transform(["AI is powerful enough"])

print(vectorizer.get_feature_names_out())
# print(X)

"""
## 🧠 POS Tagging

### 📌 Definition
Identifies grammatical role of words

Example:
"I run fast"

I → Pronoun  
run → Verb  
fast → Adverb
"""

import nltk
# nltk.download('averaged_perceptron_tagger')

# words = ["I", "run", "fast"]
print(nltk.pos_tag(words))

"""| Tag | Category | Meaning | Example |
|-----|----------|--------|--------|
| NN  | Noun | Common noun (singular) | dog, city |
| NNS | Noun | Common noun (plural) | dogs |
| NNP | Noun | Proper noun | India, Delhi |
| VB  | Verb | Base form | run |
| VBD | Verb | Past tense | ran |
| VBG | Verb | -ing form | running |
| VBN | Verb | Past participle | eaten |
| VBZ | Verb | 3rd person singular | runs |
| PRP | Pronoun | Personal pronoun | I, he, they |
| JJ  | Descriptor | Adjective | big, fast |
| RB  | Descriptor | Adverb | quickly |
| IN  | Structure | Preposition | in, on, at |
| DT  | Structure | Determiner | the, a |

## 🏷️ Named Entity Recognition (NER)

### 📌 Definition
Detects real-world entities

Example:
"Elon Musk lives in USA"

Elon Musk → PERSON  
USA → LOCATION
"""

import spacy
nlp = spacy.load("en_core_web_sm")
text = """
The North Atlantic Treaty Organization (NATO)[a] is an intergovernmental military alliance between 32 member states—30 in Europe and two in North America. Founded in the aftermath of World War II, NATO was established with the signing of the North Atlantic Treaty in 1949. The organization serves as a system of collective security and deterrence, whereby its independent members agree to defend each-other from attack by any outside party. This is enshrined in Article 5 of the treaty, which states that an armed attack against the territory of one member shall be considered an attack against them all.
Throughout the Cold War, NATO's primary purpose was to deter and counter the threat posed by the Soviet Union and its satellite states, which formed the rival Warsaw Pact in 1955. Following the dissolution of the Soviet Union in 1991, the alliance adapted. NATO undertook its first military intervention in the Bosnian War (1992–1995); with a United Nations mandate, it enforced a no-fly zone and defended UN safe zones. NATO also intervened in the Kosovo War in 1999 by bombing Yugoslavia with the stated goal of ending the violence and repressive actions by the Milošević government. Article 5 was invoked for the first and only time by the United States after the September 11 attacks, leading to NATO involvement in the War in Afghanistan (2001–2014), as part of the International Security Assistance Force (ISAF). In 2011, NATO intervened in the Libyan civil war, with a UN mandate to enforce a no-fly zone and protect civilians. The alliance has since been involved in training Iraq's military and countering piracy.

river bank
"""
# print(text)
doc = nlp(text)

for ent in doc.ents:
    print(ent.text, ent.label_)

"""## 🚀 Transformers (Modern NLP)

### 📌 Definition
Deep learning models that understand context better

Used in:
- ChatGPT
- BERT
- GPT

### Why important?
State-of-the-art performance

## 1. Basic Text Generation (Default)

📌 What’s happening:
- Uses default model (usually GPT-2)
- Generates continuation of input text
"""

from transformers import pipeline

generator = pipeline("text-generation")

print(generator("AI will", max_length=20))

"""## 2. Controlled Output (Temperature & Sampling)

📌 Key Parameters:
temperature → randomness (low = deterministic, high = creative)
top_k → limits vocabulary choices
top_p → nucleus sampling

👉 Use this when you want better quality + less randomness
"""

from transformers import pipeline

generator = pipeline("text-generation")

print(generator(
    "AI will",
    max_length=20,
    temperature=0.7,
    top_k=50,
    top_p=0.9
))

"""## 3. Using a Specific Model

📌 Why this matters:
Different models = different performance
gpt2-medium > default GPT-2 in quality
"""

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="gpt2-medium"
)

print(generator("AI will change the world because", max_length=30))

"""## 🔁 4. Multiple Outputs (n variations)

📌 Use case:
Brainstorming ideas
Generating multiple responses
Creative applications
"""

from transformers import pipeline

generator = pipeline("text-generation")

outputs = generator(
    "AI will",
    max_length=20,
    num_return_sequences=3
)

for i, o in enumerate(outputs):
    print(f"Output {i+1}: {o['generated_text']}")